language: scala
scala:
- 2.11.8
- 2.12.0
jdk:
- oraclejdk8
before_install:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_86276aecec54_key -iv $encrypted_86276aecec54_iv
  -in secring.gpg.enc -out secring.gpg -d; fi
script:
- sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport

after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then sbt
  compile publishSigned; fi
- if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then echo "Not in master branch, skipping
  deploy and release"; fi
- bash <(curl -s https://codecov.io/bash)