language: scala

before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash
  scripts/decrypt-keys.sh; fi
- export PATH=${PATH}:./vendor/bundle

install:
- rvm use 2.2.3 --install --fuzzy
- gem update --system
- gem install sass
- gem install jekyll -v 3.2.1

after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    sbt ++$TRAVIS_SCALA_VERSION publishSnapshot;
    bash scripts/publishMicrosite.sh;
  fi
- bash <(curl -s https://codecov.io/bash)

matrix:
  include:
    - scala: 2.11.8
      script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
    - scala: 2.12.1
      script:
        - sbt ++$TRAVIS_SCALA_VERSION clean coverage tests/test coverageReport
        - sbt ++$TRAVIS_SCALA_VERSION "docs/tut"	