language: scala
scala:
- 2.11.8
- 2.12.1
jdk:
- oraclejdk8
before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    bash scripts/decrypt-keys.sh;
  fi
- export PATH=${PATH}:./vendor/bundle
install:
- rvm use 2.2.3 --install --fuzzy
- gem update --system
- gem install sass
- gem install jekyll -v 3.2.1
script:
- sbt ++$TRAVIS_SCALA_VERSION update
- sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
- if [ "$TRAVIS_BRANCH" = "2.12.1" ]; then
    sbt ++$TRAVIS_SCALA_VERSION "docs/tut";
  fi


after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    sbt ++$TRAVIS_SCALA_VERSION depUpdateDependencyIssues;
    sbt ++$TRAVIS_SCALA_VERSION orgPublishRelease;
    sbt docs/publishMicrosite;
  fi
- bash <(curl -s https://codecov.io/bash)