name: Freestyle
baseurl: ''
description: A Cohesive & Pragmatic Framework of FP centric Scala libraries
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.0-SNAPSHOT
org: 47 Degrees
markdown: kramdown
